### PR TITLE
store tampers in feeds_importer config files instead

### PR DESCRIPTION
**Pull request by herbdool**
Addresses #1

### CODE REVIEW

**Comment by herbdool** [comment]
looking for some testing - mostly because it's a large change. @laryn @BWPanda or @jenlampton have time? Thanks!

**Comment by jenlampton** [comment]
Sorry @herbdool testing now!

**Comment by jenlampton** [comment]
Any time I hit the `Save` button on the `Mapping for Node processor` form, I get the error:
```
Call to undefined function feeds_tamper_form_feeds_ui_mapping_form_submit()
```
That said, things still seem to save as expected. 

When attempting to delete a tamper plugin (via the drop-button action), I get the error:
```
Call to undefined function feeds_tamper_plugin_instance_load()
```
And I was never able to delete it.

**Comment by jenlampton** [comment]
> And I was never able to delete it.

Since I couldn't delete the tamper, I tried to `disable` it by un-checking the box in the right-most column. Though it appeared to be disabled (the font color became gray instead of black) the tamper effect still applied to that mapping.

Screen Shot 2020-07-29 at 6 58 23 PM

**Comment by herbdool** [comment]
@jenlampton very helpful! I'll see if I can fix these

**Comment by herbdool** [comment]
I think it's all working now. I'm going to merge.

**Pull request merged**
